CREATE TABLE applicants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  dob DATE,
  gender VARCHAR(20),
  email VARCHAR(150),
  phone VARCHAR(15),
  alt_phone VARCHAR(15),
  nationality VARCHAR(50),
  address1 VARCHAR(200),
  address2 VARCHAR(200),
  city VARCHAR(100),
  state VARCHAR(100),
  country VARCHAR(100),
  pincode VARCHAR(20),
  qualification VARCHAR(100),
  university VARCHAR(150),
  passing_year INT,
  percentage VARCHAR(20),
  course VARCHAR(100),
  mode VARCHAR(50),
  timing VARCHAR(50),
  skills VARCHAR(200),
  experience INT,
  hobbies VARCHAR(200),
  comments TEXT,
  resume VARCHAR(255)
);
